name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipython
  - jupyter
  - notebook
  - jupyterlab
  - ipykernel
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - gdal
  - geopandas
  - fiona
  - rasterio
  - rasterstats
  - shapely
  - rtree
  - pyproj
  - pyshp
  - flopy
  - netcdf4
  - openpyxl
  - xlrd
  - pyyaml
  - requests
  - pooch
  - tqdm
  - pytest
  - pip